### ISSUE TITLE
How can I put and get my custom attributes from context span?

### ISSUE THREAD

**Issue by wwulfric** [open-telemetry/opentelemetry-java#1860] opened 2020-10-22 07:21 UTC
**Is your feature request related to a problem? Please describe.**
I want to put my user data to a span, and get them from span in my context.

```
+--------------+          +--------------+           +--------------+
|              | userdata |              | userdata  |              |
|  start span  +---------->   call rpc   +----------->   end span   |
|              |          |              |           |              |
+--------------+          +-------+------+           +--------------+
                                  |
                                  |
                                  |userdata
                                  |
                                  v
```

**Describe the solution you'd like**
OpenTracing has an api: https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Span.java#L137
```java
public interface Span {
    Span setBaggageItem(String key, String value);
    String getBaggageItem(String key);
}
```

**Describe alternatives you've considered**
I notice open telemetry has `setAttribute` api, could we have a `getAttribute` and `getAttrbutes` api?

**Comment by iNikem** [comment] 2020-10-22 10:59
Span is write-only by design. From [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#span):

> Spans are not meant to be used to propagate information within a process. To prevent misuse, implementations SHOULD NOT provide access to a Span's attributes besides its SpanReference.

**Comment by anuraaga** [comment] 2020-10-22 11:11
@wwulfric Thanks for filing this. @jkwatson is working on the OpenTelemetry baggage API right now, which is actually independent from spans. I don't know if it's quite stabilized yet but it should help with your use case and if not do let us know.

**Comment by wwulfric** [comment] 2020-10-22 11:52
@iNikem Thanks. What I need is not read from span, but get the customized user data in context. The Baggage does this work.

@anuraaga Yes I've noticed it. And Baggage seems not work well in 0.9.1. Because there is only EmptyBaggage right now.

**Comment by wwulfric** [comment] 2020-10-22 12:42
@jkwatson Hi, I find that in BaggageSdk, getEntries return an unmodified collection. Does it mean that putting entries into baggage is not recommanded?

**Comment by jkwatson** [comment] 2020-10-22 15:15
Baggage is just recently fully implemented in the API. It's available via the latest snapshot builds, and will be available when we release 0.10.0 in a week or so. 

With 0.9.1, Baggage will only be functional if you have the SDK installed, but then should work ok (although the APIs have changed significantly for 0.10.0-SNAPSHOT).

**Comment by jkwatson** [comment] 2020-10-22 15:17
> @jkwatson Hi, I find that in BaggageSdk, getEntries return an unmodified collection. Does it mean that putting entries into baggage is not recommanded?

Baggage itself is immutable. If you need to add/remove items, you need to create a new Baggage via the builder. Which reminds me, we probably need a `toBuilder()` method on the Baggage API.

**Comment by wwulfric** [comment] 2020-10-23 01:53
@jkwatson What does `have the SDK installed` mean? I found BaggageSdk is not avaiable publicly, then I copy it and use its builder. It seems a wrong useage...

**Comment by jkwatson** [comment] 2020-10-23 02:29
> @jkwatson What does `have the SDK installed` mean? I found BaggageSdk is not avaiable publicly, then I copy it and use its builder. It seems a wrong useage...
> 
> UPDATE:
> Got it. I need to set io.opentelemetry.sdk.baggage.spi.BaggageManagerFactorySdk as spi in META-INF/services.

Right, and that should be done out of the box if you have the SDK jar on your classpath.

**Comment by wwulfric** [comment] 2020-10-27 06:59
@jkwatson What's the best way to associate context, baggage and span?

```java
// extract context from carrier
Context extractedContext = OpenTelemetry.getPropagators().getTextMapPropagator()
            .extract(Context.current(), httpRequest, getter);
// build baggage
Baggage currentBaggage = OpenTelemetry.getBaggageManager().baggageBuilder().put(xxx).build();
// override extractedContext
extractedContext = BaggageUtils.withBaggage(currentBaggage, extractedContext);
// set extractedContext to current context
try (Scope scope = ContextUtils.withScopedContext(extractedContext)) {
    Span serverSpan = getTracer().spanBuilder(httpRequest.getRequestURI()).setSpanKind(Span.Kind.SERVER)
                .startSpan();
}
```

It seems `TracingContextUtils.getCurrentSpan()` result is a DefaultSpan, which is invalid.

I change the order:
```java
// extract context from carrier
Context extractedContext = OpenTelemetry.getPropagators().getTextMapPropagator()
            .extract(Context.current(), httpRequest, getter);
// build baggage
Baggage currentBaggage = OpenTelemetry.getBaggageManager().baggageBuilder().put(xxx).build();
// start span from context
Span serverSpan = getTracer().spanBuilder(httpRequest.getRequestURI()).setSpanKind(Span.Kind.SERVER)
            .setParent(extractedContext)
            .startSpan();
 try (Scope scope = TracingContextUtils.currentContextWith(serverSpan)) {
            Scope scope2 = BaggageUtils.currentContextWith(currentBaggage);
}
```
And it works. But the scope is changed.

**Comment by jkwatson** [comment] 2020-10-27 16:01
I'm not sure if your bottom example got munged/truncated, but you aren't closing the 2nd scope in that code. You *must* close every scope that is opened. So, another try-with-resources is needed for `scope2`.

**Comment by jkwatson** [comment] 2021-03-05 20:51
Closing, as the Baggage API supports the use-case.

**Closed by jkwatson** 2021-03-05 20:51 UTC
Labels: Feature Request

**Comment by SimoneGiusso** [comment] 2023-07-24 15:43
> Closing, as the Baggage API supports the use-case.

@jkwatson I think anyway that the SPI provided by OpenTracing was easier. In the [doc](https://opentelemetry.io/docs/instrumentation/java/manual/) with have this example to extract data propagated:

```java
  // Extract the SpanContext and other elements from the request.
  Context extractedContext = openTelemetry.getPropagators().getTextMapPropagator()
        .extract(Context.current(), httpExchange, getter);

// String propagatedhttpMethod = extractedContext.get(ContextKey.named(SemanticAttributes.HTTP_METHOD)) 
```

I would instead simply calling `httpExchange.getRequestHeaders().get(SemanticAttributes.HTTP_METHOD).get(0);` instead at this point (look easier that the example above).

I'm migrating from OpenTracing to OpenTelemetry and I have an utility class where to get an info propagated I simply have to call:

```java
    private static Optional<String> getBaggageItem(String key) {
        return Optional.ofNullable(GlobalTracer.get().activeSpan()).map(span -> span.getBaggageItem(key));
    }
```

However with OpenTelemetry I should get the "carrier" first. So I'd have to retrieve the httpExchange, making the code more complicated.

**Comment by SimoneGiusso** [comment] 2023-07-24 16:35
> In order to get the baggage from the current context, you just say Baggage.current(). Hard to imagine a simpler API than that!

Is there an example of set/get? I didn't find any examples in doc.

**Comment by SimoneGiusso** [comment] 2023-07-27 10:01
> You should separate these two concepts. Extraction of the data from a carrier is a distinct activity from extraction of baggage from a Context.
> 
> In order to get the baggage from the current context, you just say Baggage.current(). Hard to imagine a simpler API than that!

@jkwatson I can see there is a get method in the `Baggage` API (`getEntryValue`) but no set method? Basically the code I'm trying to migrate is showed [here](https://github.com/open-telemetry/opentelemetry-java/discussions/5651).

**Comment by jkwatson** [comment] 2023-07-27 16:36
Baggage is immutable so you can't set a value on an existing instance. The OTel APIs are very different than open tracing. I recommend spending some time understanding how our Context works, as OTel Baggage is not associated with spans, but with the Context.

**Comment by SimoneGiusso** [comment] 2023-07-28 10:20
@jkwatson 

> The OTel APIs are very different than open tracing. 

I got this. In the first message I posted on this thread I was challenging two things:

1. The complexity of this new API and the old open tracing api (which btw it may not be strictly related to this thread).
2. The fact that this issue should be really closed as _the Baggage API supports the use-case._. This bring me [here](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md#propagation), in the baggage propagation section, for which I found this [section](https://opentelemetry.io/docs/instrumentation/java/manual/#context-propagation) dedicated to java. Here a `carrier` is required, however the OpenTracing API don't have this concept. What if I don't have the concept of carrier in my code? This won't support my use case. And why it this necessary for the current API. Can the current API be simplified. Transition from OpenTracing to OpenTelemetry is not easier here. And again this I got it (which is also mentioned in the migration guide [here](https://opentelemetry.io/docs/migration/opentracing/#baggage)).

So can really OpenTelemetry support the same use case mentioned in the top of this thread. Yes it does with some limitations though, it requires more elements to perform the same result, what if this elements are not available in existing code?

**Comment by jkwatson** [comment] 2023-07-28 16:46
You can't not have a Carrier. Something has to actually carry the baggage entries on the wire. It might be http headers or it might be something else (Kafka metadata for example). 

If you don't have a carrier to transmit the baggage entries, how are they entering your system?

The OTel APIs can certainly support extracting baggage (via the propagator API), creation (via the builder), modification (via toBuilder), and insertion to an outgoing carrier (via the Propagator API). 

You can't do things the same way as in OT, but the capabilities are all there, perfectly symmetric with the corresponding OTel Span API. I also find the API quite simple once you take the time to understand how they work.
