### ISSUE TITLE
In-memory Exporter shutdown behavior

### ISSUE THREAD

**Issue by kbrockhoff** [open-telemetry/opentelemetry-java#536] opened 2019-09-14 22:42 UTC
I was surprised that calling shutdown on the exporter called shutdown on the tracer. On my first pass, I created an exporter per test class and then called shutdown at the end of the test run for cleanup. The objective being to keep each test clean of side effects.

It took hours to figure out the problem. When I ran single classes inside the IDE no problems but running a command line build of the entire project always failed.

If after further analysis, it makes sense to leave the tracer shutdown code, then the logging message needs to be enhanced so other users don't make the same mistake I did.

**Comment by carlosalberto** [comment] 2019-10-10 19:07
Hey @kbrockhoff 

Sorry for the late answer - so I went and check our exporters, and couldn't reproduce this. Also, I went through the code - `InMemorySpanExporter`, `DisruptorAsyncSpanProcessor`, `BatchSpansProcessor` do not even have a reference to their parent `Tracer`, so this shouldn't be possible.

However, let me know if you still have a test case - maybe there's something indirectly (involuntarily) shutting down the `Tracer` ;(

**Comment by carlosalberto** [comment] 2019-10-10 19:10
(Unless you are talking about `InMemoryTracing` and its `shutdown()` method, which indeed closes its `Tracer`. Let me know if this is the case, as this is the expected behavior, and it would mean we need to expand the docs for it ;) )

**Comment by kbrockhoff** [comment] 2019-10-12 14:40
I am talking about the shutdown() method. Since this is working as designed, expanding the docs is the solution.

**Comment by bogdandrutu** [comment] 2020-02-25 00:50
@carlosalberto or @kbrockhoff can you do a quick fix for this?

**Comment by bogdandrutu** [comment] 2020-04-01 02:47
Ping @carlosalberto :)

**Closed** 2020-09-09 23:59 UTC
Labels: priority:p3, release:required-for-ga
