### ISSUE TITLE
Implement BatchObserver

### ISSUE THREAD

**Issue by thisthat** [open-telemetry/opentelemetry-java#1644] opened 2020-09-15 08:55 UTC
We miss the [Batch observer](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/metrics/api.md#batch-observer) in the Metric API.

**Comment by jkwatson** [comment] 2020-09-15 16:00
dupe of #1331. :)

**Closed by jkwatson** 2020-09-15 16:00 UTC
Labels: Feature Request, duplicate, priority:p1, release:required-for-ga
