### ISSUE TITLE
About Metrics : max duration.

### ISSUE THREAD

**Issue by chenjazz** [open-telemetry/opentelemetry-java#4182] opened 2022-02-17 12:14 UTC
If I want to send server request's max duration .Which type can I use?

I find `LongCounter` can not set a custom value.

**Comment by jack-berg** [comment] 2022-02-18 00:09
[Histograms](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/datamodel.md#histogram) have a min / max that are part of the data model, but which have not [yet made it](https://github.com/open-telemetry/opentelemetry-proto/pull/279) to the OTLP protos. Once min/max support is available, I'd say use a histogram to record the duration of all a server's request durations. If a histogram is too heavy weight, you'd be able to configure a single bucket histogram, which essentially just provides a summary style metric capturing min, max, sum, and count.

In the mean time, your best bet may be to use a gauge that reports the max in a callback. Something along the lines of:
```
    AtomicLong maxDuration = new AtomicLong(0);
    meter.gaugeBuilder("http.server.duration.max")
        .ofLongs()
        .buildWithCallback(measurement -> {
          measurement.record(maxDuration.getAndSet(0));
        });

    .....
   
    maxDuration.set(Math.max(maxDuration.get(), duration));
```

**Comment by jack-berg** [comment] 2022-04-07 16:40
This is a duplicate of #4267. As of now, `HistogramPointData` has `getMin()` and `getMax()` versions. Once new protos are published to include [this PR](https://github.com/open-telemetry/opentelemetry-proto/pull/279), we'll propagate min and max onto histogram OTLP messages.

**Closed by jack-berg** 2022-04-07 16:40 UTC
Labels: Feature Request
