### ISSUE TITLE
Support OpenCensus -> OpenTelemetry migration path

### ISSUE THREAD

**Issue by nilebox** [open-telemetry/opentelemetry-java#2012] opened 2020-11-05 01:30 UTC
**Is your feature request related to a problem? Please describe.**
The [OpenTelemetry merger announcement](https://opensource.googleblog.com/2019/05/opentelemetry-merger-of-opencensus-and.html) promised straightforward backwards compatibility with OpenCensus.

We need to provide support for libraries which are currently instrumented via OpenCensus APIs to deliver their data to OpenTelemetry pipeline.

**Describe the solution you'd like**
#1863 Is the first "shim" version which has been merged.
It has a problem of using expiring cache which may not work well for use cases with high QPS.
We may try to implement `TracerImpl` which wouldn't use any "impl" code from OpenCensus at all (or use it minimally without requiring a cache).

**Additional context**
See discussion in #1863 for more information.

**Comment by bogdandrutu** [comment] 2020-11-05 01:51
@nilebox can this be closed as duplicate of https://github.com/open-telemetry/opentelemetry-java/issues/2013 or the other one, and move the comments to here?

**Closed** 2020-11-05 02:11 UTC
Labels: Feature Request
