### ISSUE TITLE
Replace usages of java.util.Timer with a ScheduledExecutor in the BatchSpanProcessor

### ISSUE THREAD

**Issue by jkwatson** [open-telemetry/opentelemetry-java#1560] opened 2020-08-19 15:54 UTC
The Timer has known issues with clock changes. We should use ScheduledExecutors as they are the more modern construct for doing timed executions.

**Comment by anuraaga** [comment] 2020-08-20 14:06
Is this a dupe of #729?

**Comment by malafeev** [comment] 2020-08-25 05:48
I can do it, please assign to me to proceed.

**Comment by iNikem** [comment] 2020-08-25 05:50
There are already 2 PRs addressing this issue :)

**Closed** 2020-08-26 15:22 UTC
Labels: help wanted, priority:p2, release:required-for-ga
