### ISSUE TITLE
build project failed, can not find the package(io.opentelemetry.proto.metrics.v1.internal)

### ISSUE THREAD

**Issue by HiCubee** [open-telemetry/opentelemetry-java#4399] opened 2022-04-20 03:27 UTC
I'm trying to include opentelemetry with source code, but there is some class doesn't exist

`import io.opentelemetry.proto.metrics.v1.internal.SummaryDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogramDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogramDataPoint;
import io.opentelemetry.proto.metrics.v1.internal.ExponentialHistogram;
import io.opentelemetry.proto.metrics.v1.internal.Gauge;
import io.opentelemetry.proto.metrics.v1.internal.HistogramDataPoint;`

these file used in opentelemetry-java/exporters/otpl/common

Anyone help me ? thanks!

**Comment by jack-berg** [comment] 2022-04-20 18:29
Duplicate of #4394, which has been closed.

**Closed by jack-berg** 2022-04-20 18:29 UTC
