### ISSUE TITLE
SDK: Determine how to convert OpenTelemetry::Resources into Jaeger

### ISSUE THREAD

**Issue by jpkrohling** [open-telemetry/opentelemetry-java#486] opened 2019-08-13 07:45 UTC
During the review for #481, the topic about converting OpenTelemetry Resources into Jaeger came up. Once it's clear what's to be done, the Adapter's `toJaeger` method needs to incorporate this conversion.

Context:
https://github.com/open-telemetry/opentelemetry-java/pull/481#discussion_r312575248

**Comment by pavolloffay** [comment] 2019-08-15 13:24
The resource is set on only on tracer at the moment. We can treat it as process information which maps to `Process` struct in Jager. We could get the resource from the first span and merge it with the process created at exporter startup. We do the same in Jaeger client exporters.

**Comment by songy23** [comment] 2019-09-10 17:42
FYI in opentelemetry-service we translate resource into Jaeger process tags: https://github.com/open-telemetry/opentelemetry-service/pull/325.

**Comment by thisthat** [comment] 2020-09-04 14:24
https://github.com/open-telemetry/opentelemetry-specification/issues/848 has been resolved. Resources must be mapped to process tags: [spec link](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/sdk_exporters/jaeger.md).

**Comment by jkwatson** [comment] 2020-09-14 20:55
We should probably change the title of this issue to match the fact that it just needs to be implemented now.  :)

**Comment by jkwatson** [comment] 2020-09-14 20:57
Aha. This is now a dupe of #1609 . I'll revert the title change for this issue and close it, now that the spec is done.

**Comment by jkwatson** [comment] 2020-09-14 20:58
Closing, now that the spec is complete and #1609 is ready to be implemented.

**Closed by jkwatson** 2020-09-14 20:58 UTC
Labels: SDK, priority:p2, release:required-for-ga
