### ISSUE TITLE
OtelToZipkinSpanTransformer does not attach ResourceAttributes

### ISSUE THREAD

**Issue by jonatan-ivanov** [open-telemetry/opentelemetry-java#5588] opened 2023-06-30 22:08 UTC
**Describe the bug**
If I use the Jaeger Exporter, I see the following resource attributes on spans:
```
telemetry.sdk.language
telemetry.sdk.name
telemetry.sdk.version
```
But if I use the Zipkin Exporter, these resource attributes are missing. I think this is because 
[`OtelToZipkinSpanTransformer`](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/zipkin/src/main/java/io/opentelemetry/exporter/zipkin/OtelToZipkinSpanTransformer.java) does not add them to the span as tags. According to the [docs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#telemetry-sdk) these values are mandatory for the SDK so I think the Zipkin Exporter should not just drop them.

**Steps to reproduce**
Send some spans using the Zipkin Exporter.

**What did you expect to see?**
The mandatory resource attributes should be added to Zipkin spans as tags.

**What did you see instead?**
Those tags are missing.

**What version and what artifacts are you using?**
Artifacts: `opentelemetry-sdk`, `opentelemetry-exporter-zipkin`
Version: `1.27.0`
How did you reference these artifacts?
```
implementation 'io.opentelemetry:opentelemetry-exporter-zipkin'
```

**Environment**
Java: `liberica-17.0.7+7`
```
❯ java --version
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (build 17.0.7+7-LTS, mixed mode, sharing)
```
OS: Mac OS 13.4.1

**Additional context**
N/A

**Comment by jkwatson** [comment] 2023-07-05 15:21
Currently, it's not specced what to do with resource attributes in zipkin: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk_exporters/zipkin.md

**Comment by jonatan-ivanov** [comment] 2023-07-12 04:46
Shouldn't it tough? I would assume this hasn't been specced yet but since the spec you linked seems stable, I'm questioning this assumption. Are there intentions to fix this?

Since the [docs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/resource/semantic_conventions/README.md#telemetry-sdk) are saying that these values are mandatory for the SDK, I think the Zipkin Exporter should not drop them.

**Comment by jack-berg** [comment] 2023-07-12 19:09
There's a [spec issue](https://github.com/open-telemetry/opentelemetry-specification/issues/1196) tracking this but it hasn't received much attention / feedback. I'd support an effort to help resolve this at the spec level.

**Comment by jack-berg** [comment] 2023-07-20 16:38
Realized this is a duplicate of #3009.

**Closed by jack-berg** 2023-07-20 16:38 UTC
Labels: Bug
