### ISSUE TITLE
OTLP exporter is not setting INTERNAL span kind

### ISSUE THREAD

**Issue by trask** [open-telemetry/opentelemetry-java#1055] opened 2020-03-30 03:42 UTC
See `SPAN_KIND_UNSPECIFIED` in the collector log below:

```
2020-03-29T19:54:41.967-0700    INFO    loggingexporter/logging_exporter.go:104 TraceData with 1 spans, resource "" (0 labels)
        {"exporter": "logging"}
2020-03-29T19:54:41.967-0700    DEBUG   loggingexporter/logging_exporter.go:144 Span #0
    Trace ID       : 7d90f78c2a5eff240a6dfe589c0bf48f
    Parent ID      : 0000000000000000
    ID             : 5ca22cc7ad543272
    Name           : Start my wonderful use case
    Kind           : SPAN_KIND_UNSPECIFIED
    Start time     : seconds:1585536880 nanos:664692527 
    End time       : seconds:1585536881 nanos:670076452 
    Status code    : 0
    Status message : 
    Span attributes: 
         -> attribute1: int_value:123 
        {"exporter": "logging"}
```

**Comment by jkwatson** [comment] 2020-03-30 22:28
Are we sure this an exporter issue? It looks like the exporter is doing the right thing. Could it be a collector ingest issue?

**Comment by bogdandrutu** [comment] 2020-03-31 16:41
@jkwatson indeed the collector does not handle this correctly. Will close this issue. The problem is that collector is in a transition phase from using opencensus protos internally to using otlp, and in opencensus we did not have the internal field.

See https://github.com/open-telemetry/opentelemetry-collector/issues/754

**Closed by bogdandrutu** 2020-03-31 16:41 UTC
