### ISSUE TITLE
Allow users to create their own ZPageServer instance

### ISSUE THREAD

**Issue by williamhu99** [open-telemetry/opentelemetry-java#1498] opened 2020-08-03 22:12 UTC
**Is your feature request related to a problem? Please describe.**
At the moment, the /tracez zPage only logs spans created by the global `OpenTelemetrySdk`. This prevents users who are interested in zPages from using their own sdk.

**Describe the solution you'd like**
The `ZPageServer` class registers the zPages using the `OpenTelemetrySdk`. We should modify the class so that users can create their own `ZPageServer` instance and pass in their preferred sdk.

**Additional context**
This issue was originally brought up by John Watson [here](https://github.com/open-telemetry/opentelemetry-java/pull/1380#pullrequestreview-449089237).

**Comment by jkwatson** [comment] 2020-10-09 22:59
closing as a duplicate of #1414

**Closed by jkwatson** 2020-10-09 22:59 UTC
Labels: Feature Request, release:after-ga
