### ISSUE TITLE
Extend `XXXAttributeSetter` API to accept `Span.Builder`

### ISSUE THREAD

**Issue by iNikem** [open-telemetry/opentelemetry-java#1316] opened 2020-06-08 08:00 UTC
#758 introduced `SemanticAttributes` class which allows for type- and semantic-safe way to set span attributes. It would be amazing to have the same functionality for `Span.Builder` as well. As [it is encouraged](https://github.com/open-telemetry/opentelemetry-specification/blob/4ab7c2fb4964c14fe972b03b5bb6825573bafb24/specification/api-tracing.md#span-creation) to set attributes on a builder whenever possible.

**Comment by Oberon00** [comment] 2020-06-08 14:17
I think this is a duplicate of #1075. AFAIK there is already something in the works but it's a larger refactoring.

**Comment by iNikem** [comment] 2020-06-08 14:19
@Oberon00 do you think that we should not merge #1317 and instead to wait for #1075? I rather have this PR merged so that I can use it instrumentations repo.

**Comment by Oberon00** [comment] 2020-06-08 14:28
As I commented on your PR, I think it is still a great improvement. I don't know the current status of the #1075-related PRs though.

**Closed as completed** 2020-06-10 19:53 UTC
Labels: Feature Request
