### ISSUE TITLE
Java Logger API does not compliant with the OTel Logs Data Model

### ISSUE THREAD

**Issue by yijiem** [open-telemetry/opentelemetry-java#6626] opened 2024-08-06 23:07 UTC
Maybe this is related to https://github.com/open-telemetry/opentelemetry-java/issues/6581.

In the OTel Logs Data Model, it is specified that the Body field must support any type to preserve the semantics of structured logs emitted by the application: https://opentelemetry.io/docs/specs/otel/logs/data-model/#field-body. This is specifically useful for the application which logs a JSON-structured data i.e. map<string, any> as the Body. But the OTel Java LogRecordBuilder API does not support such a case, it only supports setting a String in the body: https://github.com/open-telemetry/opentelemetry-java/blob/main/api/all/src/main/java/io/opentelemetry/api/logs/LogRecordBuilder.java#L69-L70.

Ideally, if the LogRecordBuilder API preserves the semantics of structured data, the structure should be preserved across the stack (e.g. from application to OTel collector via OTLP and eventually the structured data gets exported to the backend log store).

Seems like there is also an [Event API](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/event-api.md) for logging structured data. But it is still a WIP and is a specialized Log API and would have the same issue in opentelemetry-java since the current API does not support structured data.

Also it seems like OTLP is able to carry structured data in [LogRecord.body](https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L167-L170).

I filed a similar issue with OTel-Cpp at: https://github.com/open-telemetry/opentelemetry-cpp/issues/3000.

**Comment by jkwatson** [comment] 2024-08-07 01:55
Yes, please see #6591

**Comment by jack-berg** [comment] 2024-08-07 20:06
Just some additional context, any value log bodies are available via `opentelemetry-api-incubator` today. See example here
https://github.com/open-telemetry/opentelemetry-java/blob/5be177df559e5a2d79a171d85e664cb061982183/api/incubator/src/test/java/io/opentelemetry/api/incubator/logs/ExtendedLogsBridgeApiUsageTest.java#L85-L135

**Comment by jack-berg** [comment] 2024-08-07 20:07
Closing as duplicate of #6591.

**Closed by jack-berg** 2024-08-07 20:07 UTC
Labels: Bug

**Comment by yijiem** [comment] 2024-08-07 20:53
Thanks! I'm wondering when exporting AnyValue log record body in OTLP format, will the structure of the log record body be preserved in OTLP's LogRecord::body field? https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/logs/v1/logs.proto#L167-L170

**Comment by jack-berg** [comment] 2024-08-07 20:59
> Thanks! I'm wondering when exporting AnyValue log record body in OTLP format, will the structure of the log record body be preserved in OTLP's LogRecord::body field?

Yup. Check out this integration test which verifies this: https://github.com/open-telemetry/opentelemetry-java/blob/5be177df559e5a2d79a171d85e664cb061982183/integration-tests/otlp/src/main/java/io/opentelemetry/integrationtest/OtlpExporterIntegrationTest.java#L654-L794
