### ISSUE TITLE
SpanWrapper (SpanData) does not snapshot the value of hasEnded.

### ISSUE THREAD

**Issue by Oberon00** [open-telemetry/opentelemetry-java#1479] opened 2020-07-29 16:42 UTC
**Describe the bug**
`io.opentelemetry.sdk.trace.SpanWrapper` does not store the value of `hasEnded`, updates to the originial Span will be inadvertedly reflected in the SpanData.

**Steps to reproduce**

```java
SpanData sd = someSpan.toSpanData();
assertThat(sd.hasEnded()).isFalse();
someSpan.end();
assertThat(sd.hasEnded()).isFalse(); // Fails!
```

**What did you expect to see?**
No assertion failure -- `SpanData` should be immutable.

**What did you see instead?**
Assertion failure -- `SpanData` was modified.

**What version and what artifacts are you using?**
Master @ 8005c7eddd456b91023c661e8e9a9e37f641c9bb

**Additional context**
This can cause trouble when working with un-ended spans and multiple threads.

**Comment by bogdandrutu** [comment] 2020-07-30 02:18
Haha 👍 I would like to close this as "working as intended" :)

SpanData is an immutable snapshot of the current Span, all data recorded after that will not reflect in SpanData.

**Comment by iNikem** [comment] 2020-07-30 05:22
@bogdandrutu I think the original report was exactly that `SpanData` is NOT immutable right now.

**Comment by Oberon00** [comment] 2020-07-30 06:36
Yes, maybe "preserve" was not the best word choice. It inadvertedly reflects changing hasEnded in the Span.

**Comment by Oberon00** [comment] 2020-07-30 08:07
After reading the code, it seems that name and endTimestamp are also read from the span instead of being part of the snapshot. Also, I couldn't find any unit tests that would guard against changes to any span property being reflected in the SpanData.

I will prepare a PR.

**Comment by carlosalberto** [comment] 2020-07-30 12:58
> SpanData is an immutable snapshot of the current Span

Oh my, I totally oversaw the fact this is against `SpanData` directly, not `Span` returning an outdated `SpanData` ;) So yes, this is not an actual bug.

**Comment by Oberon00** [comment] 2020-07-30 13:01
I think it is a bug. The `@Immutable` annotation on SpanData/SpanWrapper is violated.

**Closed** 2020-07-30 22:22 UTC
Labels: Bug, priority:p3, release:required-for-ga
