### ISSUE TITLE
OTLP-HTTP exporter does not work with New Relic

### ISSUE THREAD

**Issue by rickardoberg** [open-telemetry/opentelemetry-java#6158] opened 2024-01-17 09:23 UTC
**Describe the bug**
Using the OTLP-HTTP exporter fails when sending data to New Relic. The issue appears to be that NR does not support http2, and since JdkHttpSender does not specify protocol when creating the HttpClient it will try http2 first. This causes quite a bit of exception logging.

**Steps to reproduce**
Use the OTLP-HTTP exporter, send data to a New Relic ingestion point.

**What did you expect to see?**
I would have expected that the client would detect the http2 issue and downgrade to http silently.

**What did you see instead?**
Lots of exception logging, over and over again.

**What version and what artifacts are you using?**
Artifacts: opentelemetry-exporter-sender-jdk, OTLP-HTTP
Version: :1.34.0-alpha
How did you reference these artifacts?
Using the BOM as dependency in pom.xml

**Environment**
Compiler: Amazon Corretto 17.0.10
OS: OSX 14.2.1

**Comment by rickardoberg** [comment] 2024-01-18 06:23
As a feature request along with the above, I would suggest:
1) add a protocol configuration option for the HttpSenderProvider so that it is possible to force it to HTTP1.1
2) handle the GOAWAY exceptions gracefully and don't log them when doing the fallback from HTTP2 to HTTP1.1
3) if GOAWAY is handled explicitly, see if the client config can be fixed on the fly to at least only try the wrong protocol once

**Comment by jack-berg** [comment] 2024-01-19 23:31
Hi - I'm a maintainer for this repo and also work for new relic.

> The issue appears to be that NR does not support http2

This should not be the case. New Relic's OTLP endpoint is `https://otlp.nr-data.net`. It accepts all three versions of the protocol (`grpc`, `http/protobuf`, and `http/json`) on three different ports: 4317, 4318, and 443. This is significant because grpc requires http/2. So by supporting OTLP grpc, we support http/2.

As another piece of data, we maintain a set of examples, including a [getting started guide for java](https://github.com/jack-berg/newrelic-opentelemetry-examples/tree/main/getting-started-guides/java/instrumented). I've pushed a [commit](https://github.com/jack-berg/newrelic-opentelemetry-examples/commit/56260d922046016f8599f01344b1d0985868c75e) which updates the example to use `opentelemetry-exporter-sender-okhttp` and was able to successfully export data to new relic. 

Is it possible some component in your environment is restricting you to http1.1?

**Comment by rickardoberg** [comment] 2024-01-20 00:13
Im using the JdkSender which defaults to http2. With that I am seeing GOAWAY replies on uploads. As a test I created a modified version with the only difference being setting httpclient.version to http1.1, and then it worked perfectly.

**Comment by rickardoberg** [comment] 2024-01-20 01:28
If you want to debug this I would also say that I'm using the endpoint "https://otlp.eu01.nr-data.net", if that makes any difference.

As for my environment, this is running on my laptop on my home network, so there are no environmental restrictions.

**Comment by jack-berg** [comment] 2024-01-20 01:52
Thanks for the info! Will try to recreate

**Comment by jack-berg** [comment] 2024-01-22 21:46
@rickardoberg I was able to recreate this when pointing at the `https://otlp.eu01.nr-data.net` endpoint and we're looking into it internally. It seems like some data is exported successfully, but inevitably I eventually receive `GOAWAY` errors. Downgrading to http/1.1 reliably avoids the problem, but the JDK HttpClient is already (successfully) negotiating the protocol version, and decides to continue with http/2 because the NewRelic endpoint says it supports it.

Its interesting that: 1. This only happens with the EU version of the NR endpoint. 2. This only happens with the jdk sender.

It could be the case the okhttp sender handles these types of errors silently ([as suggested here](https://stackoverflow.com/questions/65225514/handling-http-2-goaway-in-okhttp4)) while jdk sender does not, but that doesn't explain why the jdk sender only experiences this with the EU version of the endpoint. 

We're going to look into this on New Relic's side, but if this is a recurring thing for other OTLP receivers, we should consider your suggestion to "handle the GOAWAY exceptions gracefully". We could also consider allowing the protocol version to be explicitly configured, but I think we should avoid this because protocol negotiation is part of both the Jdk HttpClient and OkHttp client, and both appear to be doing it correctly.

**Comment by rickardoberg** [comment] 2024-01-22 23:47
@jack-berg That's fascinating! Yes, so that's exactly what I see as well: GOAWAY messages, but some data seems to get uploaded. And only on the EU endpoint you say? Odd. I agree that it would be best not to set the client to HTTP1.1, and that having it deal with the downgrade gracefully is better in the long run. In the short term we'll continue with our modified JdkSender until it's been resolved on the NR end. Thanks!

**Comment by jack-berg** [comment] 2024-01-24 22:02
@rickardoberg we (myself and New Relic colleagues) spent a good deal of time looking into this and have some interesting things to report:

- After extensive testing I was able to reproduce this not only on EU endpoints, but on our US endpoints as well. This contradicts my initial report that this is only happening on the EU version of the endpoint.
- The [GOAWAY](https://datatracker.ietf.org/doc/html/rfc7540#section-6.8) frame is a valid tool for servers to terminate connections. New Relic's stack has load balancers in this place which use GOAWAY as a necessary tool to shed / redistribute load.
- The GOAWAY frame includes a `Last-Stream-ID` field, which indicates the id of the latest stream the server might have taken action on. HTTP client implementations vary in terms of how they handle this. Some, like OkHttp, establish a new connection and resend streams with id >= `Last-Stream-ID`. Others, like the jdk httpclient, are simpler, and are unable to resend those streams. Instead, jdk httpclient sends a `RST_STREAM` frame back instructing the server to cancel the stream altogether. Jdk httpclient then throws a `IOException` and essentially delegates to the caller. I verified this through package captures, and found a [similar conversation](https://github.com/nosqlbench/nosqlbench/issues/401#issuecomment-1150209023) that helped me piece things together.
- The jdk http client sending `RST_STREAM` effectively cancels the stream, and so it should be safe to retry. I wasn't sure of this, but verified that new relic servers never receive the payloads of the requests which receive the `GOAWAY` jdk httpclient exception. 
- We've actually come across users reporting this error before, and reached the right conclusion (although I didn't dive this deep at the time) that the `GOAWAY` exceptions are retriable. See how this manifests in the source code [here](https://github.com/open-telemetry/opentelemetry-java/blob/main/exporters/sender/jdk/src/main/java/io/opentelemetry/exporter/sender/jdk/internal/JdkHttpSender.java#L241-L249).
- So the solution for you is actually quite simple and available right now: enable a retry policy. If performing programmatic configuration, call `OtlpHttp{Signal}ExporterBuilder#setRetryPolicy(...)` . If using autoconfigure, set `OTEL_EXPERIMENTAL_EXPORTER_OTLP_RETRY_ENABLED=true`.

I'm going to go ahead and close this issue. Please re-open if there are additional questions!

**Closed by jack-berg** 2024-01-24 22:02 UTC
Labels: Bug
