### ISSUE TITLE
Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317

### ISSUE THREAD

**Issue by siddhant16** [open-telemetry/opentelemetry-java#6620] opened 2024-08-05 22:36 UTC
I'm trying to use the `OtlpGrpcMetricExporter` in my spanner client creation. ([opentelemetry-configuration](https://github.com/googleapis/java-spanner?tab=readme-ov-file#opentelemetry-configuration))

This is how my code setup looks like,
```
    SdkMeterProvider sdkMeterProvider = SdkMeterProvider.builder()
        .registerMetricReader(PeriodicMetricReader.builder(
            OtlpGrpcMetricExporter.builder()
                .setTimeout(1000, TimeUnit.MILLISECONDS)
                .build())
            .build())
        .build();

    OpenTelemetry openTelemetry =
        OpenTelemetrySdk.builder()
            .setMeterProvider(sdkMeterProvider)
            .build();

```
However, when I'm running the application, I see that the metrics are not being exported and I get the below message,

```
Aug 05, 2024 2:19:35 PM io.opentelemetry.sdk.internal.ThrottlingLogger doLog
WARNING: Failed to export metrics. Server responded with gRPC status code 2. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
```

The spanner client is getting successfully created. I'm running a springboot application (`v3.2.1`). I have included all the required opentelemetry libraries. (`v1.39.0`)
How can I resolve this issue, so that I can see the metrics?

**Comment by siddhant16** [comment] 2024-08-06 16:49
Hi @svrnm, my springboot application is running correctly, and `localhost:8080` is active. But on `localhost:4317`, I'm not able to see the metrics. Are there any additional SystemProperties or env that I need to set apart from the above settings.

**Comment by jack-berg** [comment] 2024-08-06 17:11
> But on localhost:4317, I'm not able to see the metrics.

What are you expecting to see on `localhost:4317`? It sounds like maybe you're expecting to access that endpoint and see metrics in prometheus format? The setup you have is configuring the SDK to export metrics via [OTLP](https://opentelemetry.io/docs/specs/otlp/) `grpc` to a [collector](https://opentelemetry.io/docs/collector/) listening on port 4317. Does this match your expectations? Are you running a collector with the OTLP receiver on `localhost:4317`?

**Comment by siddhant16** [comment] 2024-08-06 17:31
Yes, right. I'm expecting to see the client side metrics mentioned **[here](https://github.com/googleapis/java-spanner?tab=readme-ov-file#available-client-side-metrics)**. Because when I use the `PrometheusHttpServer` I'm able to see like below
```
# HELP spanner_get_session_timeouts_ratio_total The number of get sessions timeouts due to pool exhaustion
# TYPE spanner_get_session_timeouts_ratio_total counter
spanner_get_session_timeouts_ratio_total{client_id="client-1",database="test-db",instance_id="test_instance",otel_scope_name="cloud.google.com/java"} 0.0
...
...
```
But I use the `OtlpGrpcMetricExporter` as mentioned in [here](https://github.com/googleapis/java-spanner?tab=readme-ov-file#opentelemetry-configuration) its not exporting the metrics to `localhost:4317`

**Comment by jack-berg** [comment] 2024-08-06 18:21
> But when I use the OtlpGrpcMetricExporter as mentioned in [here](https://github.com/googleapis/java-spanner?tab=readme-ov-file#opentelemetry-configuration) its not exporting the metrics to localhost:4317

I think you may be misunderstanding OTLP. OTLP is a push based protocol. Metrics (or spans or logs) are periodically pushed to a network location via gRPC or HTTP (with a protobuf encoded request body). The `localhost:4317` refers to the location that data is pushed to. This is in contrast to prometheus, which is a pull-based protocol. `PrometheusHttpServer` exposes metrics in on an HTTP server in your application. Scrapers are configured to periodically scrape metrics from this HTTP server, and you can go and directly access the metrics yourself to debug.

**Comment by siddhant16** [comment] 2024-08-06 18:35
Yes, right. But then how I'll be able to see/scrape the metrics as I was able to see in case of `PrometheusHttpServer` directly. 
And the Warning message itself mentions that, the metrics failed to export.

Do I need to perform any additional steps to view the metrics if I'm using the `OtlpGrpcMetricExporter`

**Comment by jack-berg** [comment] 2024-08-06 19:10
`OtlpGrpcMetricExporter ` is an entirely different paradigm than `PrometheusHttpServer`. To see the metrics, you need to configure `OtlpGrpcMetricExporter` to send them somewhere that allows you to see them. This could be the OpenTelemetry collector, configured to receive OTLP data and print debug information to the console, or an observability backend which accepts OTLP data. Prometheus also [accepts OTLP data](https://prometheus.io/blog/2024/03/14/commitment-to-opentelemetry/#otlp-ingestion-ga), so you could push the OTLP data to prometheus and query it there.

Please read docs on [collector](https://opentelemetry.io/docs/collector/) and [OTLP](https://opentelemetry.io/docs/specs/otlp/) to learn more. 

Closing this issue because the `OtlpGrpcMetricExporter` is working as intended.

**Closed by jack-berg** 2024-08-06 19:10 UTC
